'use strict';
const screens=[...document.querySelectorAll('[data-screen]')],announcement=document.querySelector('#screen-announcement'),customToggle=document.querySelector('#toggle-custom'),customPanel=document.querySelector('#custom-panel'),contentMeta=document.querySelector('#content-meta'),content=window.SecretCircleContent;
function labelScreen(screen){const heading=screen.querySelector('h2');if(heading){if(!heading.id)heading.id=`${screen.id}-heading`;heading.tabIndex=-1;screen.setAttribute('aria-labelledby',heading.id)}screen.setAttribute('aria-live','off')}
function announceVisibleScreen(){const screen=screens.find(item=>!item.hidden);if(!screen)return;const heading=screen.querySelector('h2'),target=heading||screen;requestAnimationFrame(()=>{target.focus({preventScroll:false});if(announcement)announcement.textContent=`${heading?.textContent||'Neue Ansicht'} geöffnet.`})}
for(const screen of screens)labelScreen(screen);
if(contentMeta&&content){contentMeta.textContent=`Wortpakete ${content.VERSION} · ${content.METADATA.packCount} Kategorien · ${content.METADATA.entryCount} Begriffe · intern geprüft`;contentMeta.title=content.METADATA.notice}
const observer=new MutationObserver(records=>{let screenChanged=false;for(const record of records){const target=record.target;if(record.type==='attributes'&&record.attributeName==='hidden'){if(target.matches?.('[data-screen]')&&!target.hidden)screenChanged=true;if(!target.hidden&&['next-player','next-voter'].includes(target.id))requestAnimationFrame(()=>target.focus())}}if(screenChanged)announceVisibleScreen()});
observer.observe(document.body,{subtree:true,attributes:true,attributeFilter:['hidden']});
customToggle?.setAttribute('aria-controls','custom-panel');customToggle?.setAttribute('aria-expanded',String(!customPanel?.hidden));customToggle?.addEventListener('click',()=>requestAnimationFrame(()=>customToggle.setAttribute('aria-expanded',String(!customPanel.hidden))));
document.querySelector('#show-card')?.setAttribute('aria-controls','secret');document.querySelector('#secret')?.setAttribute('aria-live','polite');document.querySelector('#secret')?.setAttribute('aria-atomic','true');document.querySelector('#time')?.setAttribute('role','timer');document.querySelector('#vote-targets')?.setAttribute('role','group');document.querySelector('#vote-targets')?.setAttribute('aria-label','Abstimmungsziele');document.querySelector('#result-word')?.setAttribute('aria-live','polite');
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;const panel=document.querySelector('#custom-panel:not([hidden])');if(panel){panel.hidden=true;customToggle?.setAttribute('aria-expanded','false');customToggle?.focus()}});
announceVisibleScreen();
