'use strict';
const E=window.SecretCircleEngine;
const KEYS={active:'secret-circle-active-v2',custom:'secret-circle-custom-v2',history:'secret-circle-history-v2',settings:'secret-circle-settings-v2'};
const WORDS={alltag:[['Schlüssel','Gegenstand'],['Regenschirm','Wetter'],['Kissen','Wohnung'],['Fahrstuhl','Gebäude'],['Zahnbürste','Bad'],['Einkaufswagen','Geschäft']],schule:[['Tafel','Unterricht'],['Pausenhof','Schule'],['Hausaufgabe','Lernen'],['Lineal','Material'],['Zeugnis','Bewertung'],['Turnhalle','Sport']],technik:[['Router','Netzwerk'],['Sensor','Messung'],['Batterie','Energie'],['Kabel','Verbindung'],['Tastatur','Eingabe'],['Satellit','Signal']],essen:[['Pizza','Gericht'],['Mango','Obst'],['Nudeln','Gericht'],['Joghurt','Kühlregal'],['Popcorn','Snack'],['Zimt','Gewürz']],reisen:[['Flughafen','Reise'],['Koffer','Gepäck'],['Hotel','Unterkunft'],['Reisepass','Dokument'],['Strand','Urlaub'],['U-Bahn','Verkehr']]};
const LABELS={alltag:'Alltag',schule:'Schule',technik:'Technik',essen:'Essen',reisen:'Reisen'};
const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
let game=null,timer=null,cardVisible=false,installPrompt=null,custom=read(KEYS.custom,[]),history=read(KEYS.history,[]);
function read(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}function remove(key){localStorage.removeItem(key)}
function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function screen(id){$$('[data-screen]').forEach(node=>node.hidden=node.id!==id)}
function setStatus(message='',error=false){const node=$('#status');node.textContent=message;node.classList.toggle('error',error)}
function categoryEntries(id){if(id==='all')return Object.values(WORDS).flat().concat(custom.flatMap(item=>item.entries));if(id.startsWith('custom:')){const item=custom.find(entry=>entry.id===id.slice(7));if(!item)throw Error('Eigene Kategorie wurde nicht gefunden.');return item.entries}if(!WORDS[id])throw Error('Kategorie wurde nicht gefunden.');return WORDS[id]}
function categoryName(id){if(id==='all')return'Gemischt';if(id.startsWith('custom:'))return custom.find(item=>item.id===id.slice(7))?.name||'Eigene Kategorie';return LABELS[id]||id}
function renderCategories(){const select=$('#category'),current=select.value;select.innerHTML='<option value="all">Gemischt</option>'+Object.keys(WORDS).map(id=>`<option value="${id}">${esc(LABELS[id])}</option>`).join('')+(custom.length?'<optgroup label="Eigene Kategorien">'+custom.map(item=>`<option value="custom:${esc(item.id)}">${esc(item.name)}</option>`).join('')+'</optgroup>':'');if([...select.options].some(option=>option.value===current))select.value=current;renderCustomList()}
function renderCustomList(){$('#custom-list').innerHTML=custom.map(item=>`<div class="custom-row"><div><strong>${esc(item.name)}</strong><span>${item.entries.length} Begriffe</span></div><button type="button" class="secondary compact" data-delete-category="${esc(item.id)}">Löschen</button></div>`).join('')||'<p class="muted">Noch keine eigenen Kategorien.</p>'}
function setupValues(){return{players:$('#players').value,category:$('#category').value,imposterCount:Number($('#imposters').value),useHint:$('#hint').checked,roundSeconds:Number($('#duration').value)*60}}
function saveSettings(){write(KEYS.settings,{players:$('#players').value,category:$('#category').value,imposterCount:$('#imposters').value,useHint:$('#hint').checked,duration:$('#duration').value})}
function restoreSettings(){const settings=read(KEYS.settings,null);if(!settings)return;$('#players').value=settings.players||$('#players').value;$('#imposters').value=settings.imposterCount||'1';$('#hint').checked=settings.useHint!==false;$('#duration').value=settings.duration||'3';renderCategories();if([...$('#category').options].some(option=>option.value===settings.category))$('#category').value=settings.category}
function saveGame(){if(game)write(KEYS.active,game);else remove(KEYS.active);updateResume()}
function updateResume(){let active=null;try{active=E.restoreGame(read(KEYS.active,null))}catch{remove(KEYS.active)}const box=$('#resume-box');box.hidden=!active;if(active)$('#resume-text').textContent=`${active.players.length} Personen · ${active.category} · ${active.phase==='reveal'?'Kartenverteilung':'Diskussion'}`}
function startGame(){setStatus();try{const values=setupValues(),entries=categoryEntries(values.category);game=E.createGame({...values,entries,category:categoryName(values.category),seed:crypto.randomUUID()});cardVisible=false;saveSettings();saveGame();showGame()}catch(error){setStatus(error.message,true)}}
function showGame(){if(!game){screen('setup-screen');return}clearTimer();if(game.phase==='reveal')renderReveal();else if(game.phase==='discussion')renderDiscussion();else renderResult()}
function renderReveal(){screen('reveal-screen');cardVisible=false;const player=game.revealOrder[game.revealIndex];$('#reveal-progress').textContent=`Karte ${game.revealIndex+1} von ${game.revealOrder.length}`;$('#player-name').textContent=player;$('#secret').hidden=true;$('#show-card').hidden=false;$('#next-player').hidden=true;$('#handoff-note').textContent='Nur diese Person darf jetzt auf den Bildschirm schauen.'}
function revealCard(){const player=game.revealOrder[game.revealIndex],role=E.roleFor(game,player);cardVisible=true;$('#role').textContent=role.label;$('#word').textContent=role.value;$('#hint-text').textContent=role.instruction;$('#secret').hidden=false;$('#show-card').hidden=true;$('#next-player').hidden=false;$('#handoff-note').textContent='Merken, Karte schließen und Gerät weitergeben.'}
function nextPlayer(){if(!cardVisible)return;game=E.advanceReveal(game);cardVisible=false;saveGame();showGame()}
function renderDiscussion(){screen('round-screen');$('#round-category').textContent=game.category;$('#round-players').textContent=`${game.players.length} Personen · ${game.imposters.length} Imposter`;updateTime();renderHistory()}
function updateTime(){const value=Math.max(0,game?.remainingSeconds||0),minutes=String(Math.floor(value/60)).padStart(2,'0'),seconds=String(value%60).padStart(2,'0');$('#time').textContent=`${minutes}:${seconds}`}
function toggleTimer(){if(timer){clearTimer();$('#timer-toggle').textContent='Timer fortsetzen';return}if(!game||game.remainingSeconds<=0)return;$('#timer-toggle').textContent='Timer pausieren';timer=setInterval(()=>{game=E.setRemaining(game,Math.max(0,game.remainingSeconds-1));updateTime();saveGame();if(game.remainingSeconds===0){clearTimer();$('#timer-toggle').textContent='Zeit abgelaufen';navigator.vibrate?.([180,100,180])}},1000)}
function clearTimer(){if(timer)clearInterval(timer);timer=null}
function completeRound(){clearTimer();game=E.completeGame(game);history=[E.historyEntry(game),...history.filter(item=>item.id!==game.id)].slice(0,10);write(KEYS.history,history);remove(KEYS.active);renderResult()}
function renderResult(){screen('result-screen');$('#result-word').textContent=game.word;$('#result-imposters').innerHTML=game.imposters.map(name=>`<li>${esc(name)}</li>`).join('');$('#result-meta').textContent=`${game.category} · ${game.players.length} Personen · ${game.imposters.length} Imposter`;renderHistory()}
function renderHistory(){const node=$('#history-list');if(!node)return;node.innerHTML=history.map(item=>`<article class="history-item"><div><strong>${esc(item.word)}</strong><span>${esc(item.category)} · ${item.playerCount} Personen</span></div><span>${esc(item.imposters.join(', '))}</span></article>`).join('')||'<p class="muted">Noch keine abgeschlossenen Runden.</p>'}
function resumeGame(){try{game=E.restoreGame(read(KEYS.active,null));showGame()}catch(error){remove(KEYS.active);updateResume();setStatus(error.message,true)}}
function newGame(){clearTimer();if(game&&game.phase!=='completed'&&!confirm('Aktuelle Runde verwerfen und neu beginnen?'))return;game=null;remove(KEYS.active);screen('setup-screen');updateResume();renderHistory()}
function addCustomCategory(event){event.preventDefault();try{const name=$('#custom-name').value.trim(),entries=E.parseCustomEntries($('#custom-words').value);if(name.length<2)throw Error('Bitte einen Kategorienamen eingeben.');custom=[...custom,{id:crypto.randomUUID(),name:name.slice(0,50),entries}];write(KEYS.custom,custom);event.currentTarget.reset();renderCategories();setStatus(`Kategorie „${name}“ gespeichert.`)}catch(error){setStatus(error.message,true)}}
function deleteCategory(id){const item=custom.find(entry=>entry.id===id);if(!item||!confirm(`Kategorie „${item.name}“ löschen?`))return;custom=custom.filter(entry=>entry.id!==id);write(KEYS.custom,custom);renderCategories()}
function updateConnection(){const online=navigator.onLine;$('#connection').textContent=online?'Online · offline bereit':'Offline-Modus';$('#connection').classList.toggle('offline',!online)}
async function installApp(){if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install-app').hidden=true}
function registerPwa(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('#install-app').hidden=false});window.addEventListener('appinstalled',()=>{$('#install-app').hidden=true;setStatus('Secret Circle wurde installiert.')});window.addEventListener('online',updateConnection);window.addEventListener('offline',updateConnection);updateConnection()}
$('#start').addEventListener('click',startGame);$('#resume').addEventListener('click',resumeGame);$('#discard-resume').addEventListener('click',()=>{remove(KEYS.active);updateResume()});$('#show-card').addEventListener('click',revealCard);$('#next-player').addEventListener('click',nextPlayer);$('#timer-toggle').addEventListener('click',toggleTimer);$('#reveal-result').addEventListener('click',completeRound);$$('[data-new-game]').forEach(button=>button.addEventListener('click',newGame));$('#custom-form').addEventListener('submit',addCustomCategory);$('#custom-list').addEventListener('click',event=>{const id=event.target.dataset.deleteCategory;if(id)deleteCategory(id)});$('#toggle-custom').addEventListener('click',()=>{$('#custom-panel').hidden=!$('#custom-panel').hidden});$('#install-app').addEventListener('click',installApp);$('#clear-history').addEventListener('click',()=>{if(confirm('Rundenverlauf löschen?')){history=[];write(KEYS.history,history);renderHistory()}});
renderCategories();restoreSettings();updateResume();renderHistory();registerPwa();screen('setup-screen');
